apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
  namespace: {{ .Values.homeCloud.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
  selector:
    app: hello-world
