apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started-app
  namespace: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: getting-started-app
  template:
    metadata:
      labels:
        app: getting-started-app
    spec:
      affinity:
        nodeAffinity: {{ toYaml .Values.homeCloud.nodeAffinity | nindent 12 }}
      containers:
        - name: getting-started-app
          image: nginx:{{ .Chart.AppVersion }}
          ports:
            - name: http
              containerPort: 80 
