apiVersion: v1
kind: Service
metadata:
  name: getting-started-app
  namespace: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
  selector:
    app: getting-started-app
