apiVersion: v1
kind: Service
metadata:
  name: searxng
  labels:
    app: searxng
  namespace: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
  selector:
    app: searxng
